swagger: "2.0"
info:
  title: Books API
  description: A simple Book management API
  version: 1.0.0
basePath: /api/v1
schemes:
  - http
paths:
  /books:
    get:
      summary: Lists all books
      operationId: getBooks
      responses:
        200:
          description: An array of books
          schema:
            type: array
            items:
              $ref: '#/definitions/Book'
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    post:
      summary: Adds a book
      operationId: addBook
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/Book"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/Book"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    delete:
      summary: Delete a book
      operationId: deleteBook
      parameters:
      - type: integer
        format: int64
        name: id
        in: query
      responses:
        201:
          description: Delete book
          schema:
            $ref: '#/definitions/Book'
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /book/{id}:
    parameters:
    - type: integer
      format: int64
      name: id
      in: path
      required: true
    get:
      summary: Return a book from ID
      operationId: getBook
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/Book"
      responses:
        200:
          description: A book
          schema:
            $ref: '#/definitions/Book'
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /checkout:
    patch:
      operationId: checkoutBook
      parameters:
      - type: integer
        format: int64
        name: id
        in: query
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Book"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /return:
    patch:
      operationId: returnBook
      parameters:
      - type: integer
        format: int64
        name: id
        in: query
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Book"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"

definitions:
  Book:
    type: object
    required:
      - id
      - title
      - author
      - quantity
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      author:
        type: string
      quantity:
        type: integer
        format: int64
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string