// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Rest_API_Swagger_Design_First/models"
)

// AddBookCreatedCode is the HTTP code returned for type AddBookCreated
const AddBookCreatedCode int = 201

/*
AddBookCreated Created

swagger:response addBookCreated
*/
type AddBookCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Book `json:"body,omitempty"`
}

// NewAddBookCreated creates AddBookCreated with default headers values
func NewAddBookCreated() *AddBookCreated {

	return &AddBookCreated{}
}

// WithPayload adds the payload to the add book created response
func (o *AddBookCreated) WithPayload(payload *models.Book) *AddBookCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add book created response
func (o *AddBookCreated) SetPayload(payload *models.Book) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddBookCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
AddBookDefault error

swagger:response addBookDefault
*/
type AddBookDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAddBookDefault creates AddBookDefault with default headers values
func NewAddBookDefault(code int) *AddBookDefault {
	if code <= 0 {
		code = 500
	}

	return &AddBookDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the add book default response
func (o *AddBookDefault) WithStatusCode(code int) *AddBookDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the add book default response
func (o *AddBookDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the add book default response
func (o *AddBookDefault) WithPayload(payload *models.Error) *AddBookDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add book default response
func (o *AddBookDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddBookDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
