// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CheckoutBookHandlerFunc turns a function with the right signature into a checkout book handler
type CheckoutBookHandlerFunc func(CheckoutBookParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CheckoutBookHandlerFunc) Handle(params CheckoutBookParams) middleware.Responder {
	return fn(params)
}

// CheckoutBookHandler interface for that can handle valid checkout book params
type CheckoutBookHandler interface {
	Handle(CheckoutBookParams) middleware.Responder
}

// NewCheckoutBook creates a new http.Handler for the checkout book operation
func NewCheckoutBook(ctx *middleware.Context, handler CheckoutBookHandler) *CheckoutBook {
	return &CheckoutBook{Context: ctx, Handler: handler}
}

/*
	CheckoutBook swagger:route PATCH /checkout checkoutBook

CheckoutBook checkout book API
*/
type CheckoutBook struct {
	Context *middleware.Context
	Handler CheckoutBookHandler
}

func (o *CheckoutBook) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCheckoutBookParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
