// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"Rest_API_Swagger_Design_First/models"
)

// DeleteBookCreatedCode is the HTTP code returned for type DeleteBookCreated
const DeleteBookCreatedCode int = 201

/*
DeleteBookCreated Delete book

swagger:response deleteBookCreated
*/
type DeleteBookCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Book `json:"body,omitempty"`
}

// NewDeleteBookCreated creates DeleteBookCreated with default headers values
func NewDeleteBookCreated() *DeleteBookCreated {

	return &DeleteBookCreated{}
}

// WithPayload adds the payload to the delete book created response
func (o *DeleteBookCreated) WithPayload(payload *models.Book) *DeleteBookCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete book created response
func (o *DeleteBookCreated) SetPayload(payload *models.Book) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBookCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
DeleteBookDefault generic error response

swagger:response deleteBookDefault
*/
type DeleteBookDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteBookDefault creates DeleteBookDefault with default headers values
func NewDeleteBookDefault(code int) *DeleteBookDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteBookDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete book default response
func (o *DeleteBookDefault) WithStatusCode(code int) *DeleteBookDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete book default response
func (o *DeleteBookDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete book default response
func (o *DeleteBookDefault) WithPayload(payload *models.Error) *DeleteBookDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete book default response
func (o *DeleteBookDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBookDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
