// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ReturnBookHandlerFunc turns a function with the right signature into a return book handler
type ReturnBookHandlerFunc func(ReturnBookParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ReturnBookHandlerFunc) Handle(params ReturnBookParams) middleware.Responder {
	return fn(params)
}

// ReturnBookHandler interface for that can handle valid return book params
type ReturnBookHandler interface {
	Handle(ReturnBookParams) middleware.Responder
}

// NewReturnBook creates a new http.Handler for the return book operation
func NewReturnBook(ctx *middleware.Context, handler ReturnBookHandler) *ReturnBook {
	return &ReturnBook{Context: ctx, Handler: handler}
}

/*
	ReturnBook swagger:route PATCH /return returnBook

ReturnBook return book API
*/
type ReturnBook struct {
	Context *middleware.Context
	Handler ReturnBookHandler
}

func (o *ReturnBook) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewReturnBookParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
