// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Books API
//
//	A simple Book management API
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /api/v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
